# SPDX-FileCopyrightText: 2023 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: ✨ Enhancement
description: Suggest an enhancement or an improvement.
title: "✨ <title>"
labels: [enhancement, triage]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Preflight checklist
      description: 
      options:
        - label: "I could not find a solution in the existing issues, docs, nor discussions."
          required: true
  - type: textarea
    attributes:
      label: Suggestion
      description: Tell us how we could improve the platform.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible Implementation
      description: Not obligatory, but ideas as to the implementation of the suggestion.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Tasks
      description: |
        ```[tasklist]
        # Tasks
        - [ ] Task 1
        ```

        ```[tasklist]
        # Master PRs
        - [ ] 
        ```

        ```[tasklist]
        # Stable PRs
        - [ ] Task 1
        ```
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Links? References? Screenshots? Possible Solution? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
