# SPDX-FileCopyrightText: 2021-2023 Eduardo Robles <edu@sequentech.io>
# SPDX-FileCopyrightText: 2022 Félix Robles <felix@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Cargo check
on:
  workflow_call:
    inputs:
      cachix-auth-identity:
        description: 'Name of a cachix cache to push and pull/substitute'
        required: true
        type: string
      command:
        description: 'Command to execute'
        default: 'cargo check'
        required: false
        type: string
    secrets:
      cachix-auth-token:
        required: true

jobs:
  check:
    name: 'Static Analysis: cargo check'
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v19
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.10.0pre20220629_b7eb4ac/install
        nix_path: nixpkgs=channel:nixos-22.05
        extra_nix_config: |
          experimental-features = nix-command flakes

    - uses: cachix/cachix-action@v12
      with:
        name: '${{ inputs.cachix-auth-identity }}'
        authToken: '${{ secrets.cachix-auth-token }}'

    - name: Run cargo check
      run: |
        nix \
          --extra-experimental-features "nix-command flakes" \
          develop \
          --command bash -c "${{ inputs.command }}"
