on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_ANNOUNCEMENTS_WEBHOOK_URL }}
          color: "2493280"
          username: "Sequent Tech"
          avatar_url: "https://cdn.discordapp.com/icons/1006401206782001273/99de6aec751f4714d85b3f683fe71e3e.webp?size=240"
          content: "||@everyone||"
          footer_title: "Release Notes"
          footer_icon_url: "https://cdn.discordapp.com/icons/1006401206782001273/99de6aec751f4714d85b3f683fe71e3e.webp?size=240"
          footer_timestamp: true