# SPDX-FileCopyrightText: 2014-2023 Eduardo Robles <edu@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: ORT
on:
  workflow_call:
    inputs:
      ort-cli-args:
        default: '--stacktrace'
        description: |
          List of arguments to pass to ORT CLI, applies to all commands.
        required: false
        type: string
      ort-cli-analyze-args:
        default: ''
        description: |
          List of arguments to pass to ORT Analyzer CLI.
        required: false
        type: string

jobs:
  ort:
    name: 'Static Analysis: Dependency License Scan with ORT'
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/

      - uses: actions/checkout@v3

      - name: Check if Cargo.lock.copy exists
        id: check_cargo_lock_copy
        uses: andstor/file-existence-action@v2
        with:
          files: Cargo.lock.copy

      - name: File exists
        if: steps.check_cargo_lock_copy.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: cp Cargo.lock.copy Cargo.lock

      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          run: > # remove the advisor step since we are not using it
            cache-dependencies,
            labels,
            analyzer,
            evaluator,
            reporter,
            upload-results
          log-level: debug
          ort-config-repository: 'https://github.com/sequentech/meta.git'
          fail-on: issues,violations
          report-formats: SpdxDocument,Excel,StaticHtml,WebApp
          image: 'ghcr.io/alliander-opensource/ort-container:date-20230401'
          ort-cli-args: ${{ inputs.ort-cli-args }}
          ort-cli-analyze-args: ${{ inputs.ort-cli-analyze-args }}
