# SPDX-FileCopyrightText: 2023 Eduardo Robles <edu@sequentech.io>
# SPDX-FileCopyrightText: 2022 Félix Robles <felix@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: update-flake-lock
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Install Nix
        uses: cachix/install-nix-action@v17
      
      - uses: cachix/cachix-action@v12
        with:
          name: sequenttech
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v16
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
