# SPDX-FileCopyrightText: 2023 Eduardo Robles <edu@sequentech.io>
# SPDX-FileCopyrightText: 2022 Félix Robles <felix@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: update-flake
on:
  workflow_call:
    inputs:
      cachix-auth-identity:
        required: true
        type: string
    secrets:
      cachix-auth-token:
        required: true
      gh-token-for-updates:
        required: true

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17
      
      - uses: cachix/cachix-action@v12
        with:
          name: '${{ inputs.cachix-auth-identity }}'
          authToken: '${{ secrets.cachix-auth-token }}'
      
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v16
        with:
          token: '${{ secrets.gh-token-for-updates }}'
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
